---
engines:
  fixme:
    enabled: true
  shellcheck:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
    - "**.sh"
    - "**.md"
exclude_paths: [
  "appdaemon/rootfs/root/appdaemon/dashboards/Hello.dash"
]
